// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNYj48UYc2ayak5vly72WUiIDOwuC9SW0',
    appId: '1:288877138466:web:71ba2ff8e93078f9c1307b',
    messagingSenderId: '288877138466',
    projectId: 'nearnest-1e1cc',
    authDomain: 'nearnest-1e1cc.firebaseapp.com',
    storageBucket: 'nearnest-1e1cc.firebasestorage.app',
    measurementId: 'G-BS5DQK58F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRp0GcdZV4a4HugYlVYveAB3fMMHcKlUo',
    appId: '1:288877138466:android:f4d45f7f736b8a1bc1307b',
    messagingSenderId: '288877138466',
    projectId: 'nearnest-1e1cc',
    storageBucket: 'nearnest-1e1cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_yFJlq5omsYLtqGyALaEfHnEfWYU0Ks8',
    appId: '1:288877138466:ios:0cd8afdc7275ad04c1307b',
    messagingSenderId: '288877138466',
    projectId: 'nearnest-1e1cc',
    storageBucket: 'nearnest-1e1cc.firebasestorage.app',
    iosBundleId: 'com.example.nearnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_yFJlq5omsYLtqGyALaEfHnEfWYU0Ks8',
    appId: '1:288877138466:ios:0cd8afdc7275ad04c1307b',
    messagingSenderId: '288877138466',
    projectId: 'nearnest-1e1cc',
    storageBucket: 'nearnest-1e1cc.firebasestorage.app',
    iosBundleId: 'com.example.nearnest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNYj48UYc2ayak5vly72WUiIDOwuC9SW0',
    appId: '1:288877138466:web:446c5ed17c85c20ac1307b',
    messagingSenderId: '288877138466',
    projectId: 'nearnest-1e1cc',
    authDomain: 'nearnest-1e1cc.firebaseapp.com',
    storageBucket: 'nearnest-1e1cc.firebasestorage.app',
    measurementId: 'G-9TMSWW7CYB',
  );
}
